name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'contracts/**'
      - 'tests/**'
      - 'Cargo.*'
      - makefile

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup Rust environment
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.69.0
          default: true
          override: true
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      # Set up Node environment
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 20.12.0
          cache: npm
      - name: Install Dependencies
        run: npm install
      # Run tests
      - name: Run tests
        run: make test

  lint:
    name: clippy and fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup Rust environment
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.69.0
          default: true
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      # Run lint
      - name: Test Format
        run: cargo fmt -- --check
      - name: Lint with clippy
        run: cargo clippy --tests -- -D clippy::all
